const constants = {
  SET_CURRENT_LISTING            : 'SET_CURRENT_LISTING',

  SET_IS_FETCHING_LISTINGS       : 'SET_IS_FETCHING_LISTINGS',

  FETCH_ALL_LISTINGS_DONE        : 'FETCH_ALL_LISTINGS_DONE',
  FETCH_ALL_LISTINGS_FAIL        : 'FETCH_ALL_LISTINGS_FAIL',

  FETCH_LISTINGS_BY_KEYWORD_DONE : 'FETCH_LISTINGS_BY_KEYWORD_DONE',
  FETCH_LISTINGS_BY_KEYWORD_FAIL : 'FETCH_LISTINGS_BY_KEYWORD_FAIL',

  FETCH_LISTING_BY_ID_DONE       : 'FETCH_LISTING_BY_ID_DONE',
  FETCH_LISTING_BY_ID_FAIL       : 'FETCH_LISTING_BY_ID_FAIL',

  UPDATE_MAP           : 'UPDATE_MAP',
  UPDATE_MAP_BOUNDS    : 'UPDATE_MAP_BOUNDS',
  UPDATE_MAP_CENTER    : 'UPDATE_MAP_CENTER',
  UPDATE_MAP_LATITUDE  : 'UPDATE_MAP_LATITUDE',
  UPDATE_MAP_LONGITUDE : 'UPDATE_MAP_LONGITUDE',
  UPDATE_MAP_ZOOM      : 'UPDATE_MAP_ZOOM',
};

export default constants;
