const constants = {
  SET_CURRENT_LISTING:   'SET_CURRENT_LISTING',

  SET_IS_FETCHING:       'SET_IS_FETCHING',

  FETCH_ALL_DONE:        'FETCH_ALL_DONE',
  FETCH_ALL_FAIL:        'FETCH_ALL_FAIL',

  FETCH_BY_KEYWORD_DONE: 'FETCH_BY_KEYWORD_DONE',
  FETCH_BY_KEYWORD_FAIL: 'FETCH_BY_KEYWORD_FAIL',
};

export default constants;
