const constants = {
  UPDATE           : 'UPDATE',
  UPDATE_BOUNDS    : 'UPDATE_BOUNDS',
  UPDATE_CENTER    : 'UPDATE_CENTER',
  UPDATE_LATITUDE  : 'UPDATE_LATITUDE',
  UPDATE_LONGITUDE : 'UPDATE_LONGITUDE',
  UPDATE_ZOOM      : 'UPDATE_ZOOM',
};

export default constants;
